### ISSUE TITLE
Want provisioning machines with delegated_dataset(s)

### ISSUE THREAD

**Issue by headw01** [joyent/terraform-provider-triton#133]
CloudAPI has been updated with the delegated_dataset feature: 
https://github.com/joyent/sdc-cloudapi/pull/64
https://github.com/joyent/sdc-cloudapi/issues/61#

Would like to use delegated datasets through the Terraform Triton Provider.

**Comment by twhiteman** [comment]
Started the process (first adding to triton-go) at https://github.com/joyent/triton-go/pull/192

**Comment by twhiteman** [comment]
Committed in fcb3c66, released in plugin 0.8.0.
