### ISSUE TITLE
Missing OpenBSD build

### ISSUE THREAD

**Issue by sreboot** [joyent/terraform-provider-triton#136]
### Terraform Version

```
$ terraform -v                                                                                                                                                                                             
Terraform v0.13.3
```

### Affected Resource(s)
triton provider

### Expected Behavior
Install triton provider on OpenBSD 

### Actual Behavior
```
Initializing modules...

Initializing the backend...

Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.

Initializing provider plugins...
- Finding latest version of joyent/triton...
- Finding latest version of -/triton...

Warning: Additional provider information from registry

The remote registry returned warnings for registry.terraform.io/-/triton:
- For users on Terraform 0.13 or greater, this provider has moved to
joyent/triton. Please update your source in required_providers.


Error: Failed to install provider

Error while installing -/triton v0.8.0: provider
registry.terraform.io/-/triton 0.8.0 is not available for openbsd_amd64


Error: Failed to install provider

Error while installing joyent/triton v0.8.0: provider
registry.terraform.io/joyent/triton 0.8.0 is not available for openbsd_amd64
```

### Steps to Reproduce
Execute terraform init on OpenBSD
1. `terraform init`

This used to work with Terraform 0.12 and provider 0.7.x.

**Comment by twhiteman** [comment]
From this warning:
```
The remote registry returned warnings for registry.terraform.io/-/triton:
- For users on Terraform 0.13 or greater, this provider has moved to
joyent/triton. Please update your source in required_providers.
```

Does changing to use that format have any affect, e.g.:
```
terraform {
  required_providers {
    triton = {
      source = "joyent/triton"
      version = "0.8.0"
    }
  }
}
```

**Comment by twhiteman** [comment]
BTW, we did publish the openbsb bits, c.f.:
https://github.com/joyent/terraform-provider-triton/releases/tag/v0.8.0

**Comment by pannon** [comment]
> From this warning:
> 
> ```
> The remote registry returned warnings for registry.terraform.io/-/triton:
> - For users on Terraform 0.13 or greater, this provider has moved to
> joyent/triton. Please update your source in required_providers.
> ```
> 
> Does changing to use that format have any affect, e.g.:
> 
> ```
> terraform {
>   required_providers {
>     triton = {
>       source = "joyent/triton"
>       version = "0.8.0"
>     }
>   }
> }
> ```

Same issue. I can only see FreeBSD bits here https://github.com/joyent/terraform-provider-triton/releases/tag/v0.8.0, OpenBSD is missing.

**Comment by twhiteman** [comment]
> Same issue - OpenBSD is missing.

Thanks for checking. Ah, I was mixing up FreeBSD and OpenBSD - my mistake. I'll dig.

**Comment by twhiteman** [comment]
Looks like the .goreleaser.yml file is missing openbsd - as the default file I copied from (when we moved the provider to the joyent repo) did not include it, c.f.
https://github.com/hashicorp/terraform-provider-scaffolding/blob/master/.goreleaser.yml

I'll add OpenBSD and make a 0.8.1 release that includes the OpenBSD bits.

**Comment by twhiteman** [comment]
The 0.8.1 is now published - so please give that a try.

**Comment by sreboot** [comment]
Worked, thank you!
