### ISSUE TITLE
Docs: triton_machine tags - terraform 0.12+ wants new block type syntax

### ISSUE THREAD

**Issue by teutat3s** [joyent/terraform-provider-triton#137]
### Terraform Version
```
Terraform v0.13.3
+ provider registry.terraform.io/joyent/triton v0.8.1
```

### Affected Resource(s)
Please list the resources as a list, for example:
- `triton_machine`

### Terraform Configuration Files

- Example from the documentation

### Debug Output
```
Error: Unsupported block type

  on main.tf line 8, in resource "triton_machine" "test-node":
   8:   tags {

Blocks of type "tags" are not expected here. Did you mean to define argument
"tags"? If so, use the equals sign to assign it a value.
```
```
Error: Unsupported block type

  on main.tf line 18, in resource "triton_machine" "test-node":
  18:   metadata {

Blocks of type "metadata" are not expected here. Did you mean to define
argument "metadata"? If so, use the equals sign to assign it a value.
```

### Expected Behavior
Terraform should accept a `tags` block for `triton_machine`

### Actual Behavior
Error of unsupported block type mentioned above.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform init`
2. `terraform validate`

**Comment by teutat3s** [comment]
https://www.terraform.io/upgrade-guides/0-12.html#attributes-vs-blocks

**Comment by twhiteman** [comment]
Thanks for the updates!
